# app/config/routing_paginas.yml
pagina_ayuda:
    path: /ayuda
    defaults: { template: 'OfertaBundle:Sitio:ayuda.html.twig' }

pagina_privacidad:
    path: /privacidad
    defaults: { template: 'OfertaBundle:Sitio:privacidad.html.twig' }

pagina_condiciones:
    path: /terminos-y-condiciones
    defaults: { template: 'OfertaBundle:Default:condiciones.html.twig' }